kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  # TODO: Fill in the persistent volume claim specifications:
  # a. storageClassName as manual
  # b. accessModes as ReadWriteMany
  # c. resource requests for storage to be 5Gi
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi