kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DBAdmin
  namespace: database # TODO: Re-run this file with other necessary ns
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DBAdminBinding
  namespace: database # TODO: Re-run this file with other necessary ns, match with role above
subjects:
  - kind: User 
    name: Jessica
roleRef:
  kind: Role
  name: DBAdmin
  apiGroup: rbac.authorization.k8s.io