apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: KubeAdmin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: KubeAdminClusterRoleBinding
subjects:
  - kind: User 
    name: Jesus
roleRef:
  kind: Role
  name: KubeAdmin
  apiGroup: rbac.authorization.k8s.io