name: Scavenger Hunt
on:
  push:
    branches:
      - "scavenger-**"

jobs:
  scavenger:
    name: Scavenger Hunt 🕵️‍♂️🔍
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout solution
        uses: actions/checkout@v3
        with:
          repository: abanuelo/intro-to-kube
          path: solution
          ref: scavenger-solution

      - name: Check results
        run: |
          STUDENT_SOLUTION=`cat ./scavenger/scavenger.json | jq ".[]" | jq ".[]" | tr -d '"' | tr "\n" ";" | tr " " "-"`
          REAL_SOLUTION=`cat ./solution/scavenger/scavenger.json | jq ".[]" | jq ".[]" | tr -d '"' | tr "\n" ";" | tr " " "-"`
          STUDENT_ARRAY=($(echo $STUDENT_SOLUTION | tr ";" "\n"))
          REAL_ARRAY=($(echo $REAL_SOLUTION | tr ";" "\n"))

          total=0
          correct=0

          for i in "${!STUDENT_ARRAY[@]}"; do
            if [ "${STUDENT_ARRAY[$i]}" == "${REAL_ARRAY[i]}" ]; then
              echo "✅ problem $i"
              total=$((total+1))
              correct=$((correct+1))
            else
              echo "❌ problem $i"
              total=$((total+1))
            fi
          done
          echo "========================================"
          echo "🎉 Total Score: $correct out of $total 🎉"
          echo "========================================"
